### ISSUE TITLE
NET CORE 2.0 

### ISSUE THREAD

**Issue by Citizen39** [WinLwinOoNet/AspNetCoreActiveDirectoryStarterKit#1]
Thanks for this Win! 

Any chance this could be updated for NET CORE 2.0?

**Comment by gomnet** [comment]
Yep! My project is already in 2.0 (I got some ideas about Identity).

Thx!!

On 31 Aug 2017 7:05 pm, "Citizen39" <notifications@github.com> wrote:

Thanks for this Win!

Any chance this could be updated for NET CORE 2.0?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/WinLwinOoNet/AspNetCoreActiveDirectoryStarterKit/issues/1>,
or mute the thread
